server:
  applicationConnectors:
    - type: http
      port: 8888
  adminConnectors:
    - type: http
      port: 8889

logging:
  level: INFO
  appenders:
    - type: console
      timeZone: CEST

defaultName: "user"
