server:
  applicationConnectors:
    - type: http
      port: 8888
  adminConnectors:
    - type: http
      port: 8889

logging:
  level: INFO
  appenders:
    - type: console
      timeZone: CET
    - type: file
      timeZone: CET
      currentLogFilename: logs/dw-seed/hello-world.log
      archivedLogFilenamePattern: logs/dw-seed/hello-world-%d.log
      archivedFileCount: 5
    - type: gelf
      host: udp:elk
      extractStackTrace: true
      filterStackTrace: true
      includeFullMDC: true

defaultName: "user"